# Generated by Django 3.2.3 on 2021-10-29 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_alpha2', models.CharField(max_length=2)),
                ('countryName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantScientificName', models.CharField(max_length=255, unique=True)),
                ('plantLocalName', models.TextField(blank=True, null=True)),
                ('pmStem', models.TextField(blank=True, null=True)),
                ('pmLeaf', models.TextField(blank=True, null=True)),
                ('pmFlower', models.TextField(blank=True, null=True)),
                ('pmFruit', models.TextField(blank=True, null=True)),
                ('plantImg', models.ImageField(blank=True, default='default.jpeg', upload_to='plantImg/')),
                ('voucher_no', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plantref', models.TextField(blank=True, null=True)),
                ('publish', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_tag', models.CharField(max_length=255, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rejection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, null=True)),
                ('plant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PlantWebApp.plant')),
            ],
        ),
        migrations.CreateModel(
            name='RecordPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(blank=True, null=True)),
                ('can_edit', models.BooleanField(blank=True, null=True)),
                ('plant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PlantWebApp.plant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_role', models.PositiveSmallIntegerField(choices=[(1, 'Admin'), (2, 'Committee'), (3, 'Researcher'), (4, 'Student')])),
                ('sv_id', models.IntegerField(blank=True, null=True)),
                ('dept', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plant_Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlantWebApp.plant')),
                ('usageID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlantWebApp.usage')),
            ],
        ),
        migrations.CreateModel(
            name='Plant_Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlantWebApp.distribution')),
                ('plantID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlantWebApp.plant')),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='distribution',
            field=models.ManyToManyField(blank=True, null=True, through='PlantWebApp.Plant_Distribution', to='PlantWebApp.Distribution'),
        ),
        migrations.AddField(
            model_name='plant',
            name='usage',
            field=models.ManyToManyField(blank=True, through='PlantWebApp.Plant_Usage', to='PlantWebApp.Usage'),
        ),
        migrations.AddField(
            model_name='plant',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
