# Generated by Django 3.2.3 on 2021-06-07 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantScientificName', models.CharField(max_length=255, unique=True)),
                ('plantLocalName', models.TextField(blank=True, null=True)),
                ('pmStem', models.TextField(blank=True, null=True)),
                ('pmLeaf', models.TextField(blank=True, null=True)),
                ('pmFlower', models.TextField(blank=True, null=True)),
                ('pmFruit', models.TextField(blank=True, null=True)),
                ('plantImg', models.ImageField(blank=True, default='default.jpeg', upload_to='plantImg/')),
                ('voucher_no', models.CharField(blank=True, max_length=100, null=True)),
                ('plantDist', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plantref', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_tag', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Plant_Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlantWebApp.plant')),
                ('usageID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlantWebApp.usage')),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='usage',
            field=models.ManyToManyField(blank=True, through='PlantWebApp.Plant_Usage', to='PlantWebApp.Usage'),
        ),
    ]
