# Generated by Django 3.2.3 on 2021-10-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlantWebApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='publish',
            new_name='admin_publish',
        ),
        migrations.AddField(
            model_name='plant',
            name='commitee_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plant',
            name='sv_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recordpermission',
            name='can_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recordpermission',
            name='can_view',
            field=models.BooleanField(default=False),
        ),
    ]
