# Generated by Django 3.2.3 on 2021-07-09 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlantWebApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
