# Generated by Django 3.2.3 on 2021-10-31 11:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlantWebApp', '0002_auto_20211030_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='research_data',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
