# Generated by Django 3.2.3 on 2021-07-15 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlantWebApp', '0002_plant_publish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_alpha2', models.CharField(max_length=2)),
                ('countryName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plant_Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlantWebApp.distribution')),
                ('plantID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlantWebApp.plant')),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='distribution',
            field=models.ManyToManyField(blank=True, null=True, through='PlantWebApp.Plant_Distribution', to='PlantWebApp.Distribution'),
        ),
    ]
