# Generated by Django 3.2.3 on 2021-07-26 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlantWebApp', '0004_auto_20210726_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rejection',
            old_name='user',
            new_name='plant',
        ),
    ]
