# Generated by Django 3.2.3 on 2021-10-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlantWebApp', '0006_remove_plant_plantdist'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
