# Generated by Django 3.2.3 on 2021-06-07 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlantWebApp', '0007_alter_plant_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='user',
            new_name='user_id',
        ),
    ]
