# Generated by Django 3.2.3 on 2021-11-09 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlantWebApp', '0008_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='commitee_approved',
            new_name='committee_approved',
        ),
        migrations.AlterField(
            model_name='images',
            name='plant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PlantWebApp.plant'),
        ),
    ]
