# Generated by Django 3.2.3 on 2021-10-08 10:01

import concurrency.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlantWebApp', '0008_profile_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='version',
            field=concurrency.fields.IntegerVersionField(default=0, help_text='record revision number'),
        ),
    ]
