# Generated by Django 3.2.3 on 2021-06-07 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlantWebApp', '0008_rename_user_plant_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='user_id',
            new_name='user',
        ),
    ]
