# Generated by Django 3.2.3 on 2021-11-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlantWebApp', '0009_auto_20211109_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='usage',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
