# Generated by Django 3.2.3 on 2021-10-09 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlantWebApp', '0009_plant_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='version',
        ),
    ]
