# Generated by Django 3.2.3 on 2021-06-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlantWebApp', '0009_rename_user_id_plant_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usage',
            name='usage_tag',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
