# Generated by Django 3.2.3 on 2021-11-17 16:38

import ckeditor.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PlantWebApp', '0013_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='research_data',
            field=ckeditor.fields.RichTextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
