# Generated by Django 3.2.3 on 2021-11-29 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlantWebApp', '0017_auto_20211129_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='collection_extract',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='collection_powder',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='collection_specimen',
        ),
    ]
