# Generated by Django 3.2.3 on 2021-12-25 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlantWebApp', '0018_auto_20211129_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='is_approved',
        ),
    ]
