# Generated by Django 3.2.3 on 2021-12-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlantWebApp', '0019_remove_permission_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='extract',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plant',
            name='oil',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plant',
            name='powder',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plant',
            name='voucher',
            field=models.IntegerField(default=0),
        ),
    ]
